### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by guanzo** [onesine/react-tailwindcss-datepicker-doc#1]
https://github.com/onesine/react-tailwindcss-datepicker-doc/blob/7f889de04e87318f1b06ca04ad72c94d003c9d06/pages/theming-options.js#L83

You can click "disappointed" to automatically change...

**Comment by onesine** [comment]
Hi @guanzo  👋

Thanks for your feedback, but I don't understand exactly what I need to change. 

What do you suggest?

**Comment by guanzo** [comment]
"You can click the buttons to automatically change.."

I don't understand what "click disappointed" means. I think you're referring to the buttons?

**Comment by onesine** [comment]
I'm really sorry.
I understand you now. I will rephrase the sentence.
